<Project>
	<PropertyGroup>
		<GenerateAssemblyInfo>true</GenerateAssemblyInfo>
		<AssemblyTitle>LateToTheParty</AssemblyTitle>
		<Authors>DanW</Authors>
		<Version>3.0.1</Version>
		<SPTVersion>~4.0.0</SPTVersion>
		<SPTGUID>com.danw.latetotheparty</SPTGUID>
		<GithubRepoPath>https://github.com/dwesterwick/SPTLateToTheParty</GithubRepoPath>
		<RelativePathToRootSPTInstall>../../</RelativePathToRootSPTInstall>
		<SPTServerDebugPath>D:\SPT\Escape from Tarkov Single Player\Source\Server\SPTarkov.Server\bin\Debug\net9.0</SPTServerDebugPath>
	</PropertyGroup>
</Project>